version: "3.9"
services:
  frontend:
    build: .
    image: "radek2s/betkeeper_frontend:latest"
    ports:
      - "3000:3000"
    links:
      - "backend"

  backend:
    build: ./backend
    image: "radek2s/betkeeper_backend:latest"
    ports:
      - "8000:8000"
