import type {
  UserFeedbackAdminResponseSchemaType,
  UserProfileSchemaType,
} from "@app/features/feedback/UserFeedbackSchema";
import { OkResponse } from "@app/lib/utils/fetchUtils";
import { getAuth } from "@app/server/auth/authenticatorFactory";
import { AuthenticationError } from "@app/server/exceptions/AuthenticationError";
import { ExceptionHandler } from "@app/server/exceptions/ExceptionHandler";
import { NextFeedbackRepository } from "@app/server/repositories/NextFeedbackRepository";
import NextUserRepository from "@app/server/repositories/NextUserRepository";

/**
 * Get all feedback messages
 * @tag Admin
 * @description Fetch all active complains or suggestions generated by users (seen are hidden)
 * @response UserFeedbackAdminResponseSchemaType
 * @openapi
 */
export async function GET(req: Request) {
  try {
    const user = await getAuth().getUser(req);
    if (user.role !== "ADMINISTRATOR")
      throw new AuthenticationError("User is not allowed to use this endpoint");

    const feedbackRepository = new NextFeedbackRepository();
    const userRepository = new NextUserRepository();

    const feedbackEntries = (await feedbackRepository.findAll()).filter(
      ({ seen }) => !seen,
    );

    if (feedbackEntries.length === 0) return OkResponse([]);

    const users = await userRepository.findAll();

    const result: UserFeedbackAdminResponseSchemaType[] = feedbackEntries.map(
      (feedback) => {
        const user = users.find(({ id }) => id === feedback.userId);
        const creatorProfile: UserProfileSchemaType = {
          id: user?.id ?? feedback.userId,
          name: user?.name ?? "",
          email: user?.email.value ?? "",
        };
        return {
          id: feedback.id,
          createdAt: feedback.createdAt.toLocaleString(),
          createdBy: creatorProfile,
          issueType: feedback.issueType,
          message: feedback.message,
          seen: feedback.seen,
        };
      },
    );

    return OkResponse(result);
  } catch (e) {
    return ExceptionHandler(e);
  }
}
