name: Continuous Integration
on:
    pull_request:
jobs:
  test-domain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run test:ci --coverage 
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}      
        with:
          name: Domain Tests            
          path: tests-results.xml
          reporter: jest-junit
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: './coverage/coverage.json'
          token: ${{ secrets.CODECOV_TOKEN }}    
      
